---
abstract: 'Add a BUGS section to refer to bugtracker (or RT as default)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Bugs-DefaultRT
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Role::Section: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-Section-Bugs-DefaultRT
  homepage: https://metacpan.org/release/Pod-Weaver-Section-Bugs-DefaultRT
  repository: git://github.com/sharyanto/perl-Pod-Weaver-Section-Bugs-DefaultRT.git
version: 0.02
